### ISSUE TITLE
Ask button not working

### ISSUE THREAD

**Issue by nckofkin** [bajuz/Tumblr-Themes#1]
Hello, I have your Tumblr theme installed on my website. There is an option for an ask button that doubles as a contact form, however it states that the page cannot be found. I would like to use this feature.

**Comment by brennenjoy** [comment]
I have the same issue as above with your Reflection theme!

**Comment by nckofkin** [comment]
Hey I think I figured it out. You have to enable the ask feature in your tumblr settings! https://www.tumblr.com/docs/en/using_messages
